### ISSUE TITLE
[구현] ROOM 생성

### ISSUE THREAD

**Issue by LeeMineo** [Team-Armigo/TEAM_Armigo#11]
RoomCreate씬의 Create Room버튼을 누르면 방이 생성. 대기실로 이동
비밀번호 설정

**Comment by LeeMineo** [comment]
[순서]
RoomCreate Scene에서 Room Name, Max Player, Password입력 후 Create Room Button을 누르면..
1. 3가지 정보를 스크립트가 인식
2. Room 생성 및 포톤 매니저 시작
3. 방 입장 ( 씬 이동)

**Comment by Jeremy-0204** [comment]
## 커스텀 프로퍼티
비밀번호를 사용하는 비밀방 만들때 유용할 듯!

- https://support.photonengine.jp/hc/ko/articles/215913128-%EB%A3%B8%EC%9D%98-%EC%BB%A4%EC%8A%A4%ED%85%80-%ED%94%84%EB%A1%9C%ED%8D%BC%ED%8B%B0-%EC%9D%B4%EC%9A%A9%ED%95%98%EA%B8%B0

- https://forum.photonengine.com/discussion/17860/rooms-with-password

- https://photonkr.tistory.com/23?category=1030095

**Comment by LeeMineo** [comment]
https://mingyu0403.tistory.com/312

https://ojui.tistory.com/41

참고할만한 자료들

**Comment by LeeMineo** [comment]
RoomData 스크립트로 방 생성 정보를 받고 버튼 클릭시 방 생성 기능을 구현한 후 , 버튼에다가 씬 넘어가는 기능과 방생성 기능 둘다 붙여놓는다.

**Comment by LeeMineo** [comment]
Room 생성 완료. 그러나 생성 시 데이터를 불러와야하는 문제에 직면. 데이터 저장 방법에 대해 찾아보자.

**Comment by LeeMineo** [comment]
https://simpleneed.tistory.com/126

**Comment by LeeMineo** [comment]
구현완료!
