### ISSUE TITLE
[문제] 빌드 문제

### ISSUE THREAD

**Issue by LeeMineo** [Team-Armigo/TEAM_Armigo#18]
구글 파이어베이스가 아직 공식적으로 실리콘 버전을 지원하지 않기 때문에 m1 유니티에선 파이어베이스를 쓸 수 없다고 한다. 

https://github.com/firebase/firebase-unity-sdk/issues/278

**Comment by LeeMineo** [comment]
Internal build system error. Backend exited with code 2.
tundra: error: Unexpected stdin

이런식으로 오류가 뜬다.

**Comment by LeeMineo** [comment]
해결방법
1.https://qiita.com/atr-toru/items/b65647993a022b966175 (일본어)
2.처음 프로젝트를 실행시킬때 이 에러는 뜨지 않는다. 그러므로 계속 업데이트 할 때 마다 프로젝트를 껐다가 킨다.

**Comment by LeeMineo** [comment]
I had the same problem. I fixed this by completely removing the "Bee" folder located in your project: Project\Library\Bee
라는 답변을 보았다. 한번 실험해보겠다.

**Comment by LeeMineo** [comment]
파이썬 에러가 떠서 파이썬을 깔았다.

**Comment by LeeMineo** [comment]
Starting a Gradle Daemon, 2 stopped Daemons could not be reused, use --status for details
에러를 해결해보자.

**Comment by LeeMineo** [comment]
https://velog.io/@ymsection/Unity-Android-빌드시-Error-The-Option-Android.Enabler8-Is-Deprecated-blah-blah

여기를 참고하면 된다.

**Comment by LeeMineo** [comment]
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':launcher'.
> Could not resolve all artifacts for configuration ':launcher:classpath'.
   > Could not find com.android.tools.build:gradle:6.1.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/6.1.1/gradle-6.1.1.pom
       - https://jcenter.bintray.com/com/android/tools/build/gradle/6.1.1/gradle-6.1.1.pom
     Required by:
         project :launcher

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

**Comment by Jeremy-0204** [comment]
경륜 빌드 문제
[현재 상황]
구글 로그인 구현 X
Preference - JDK installed with Unity 비활성화

```
C:\Program Files\Unity\Hub\Editor\2021.3.6f1\Editor\Data\il2cpp\build\deploy\il2cpp.exe --convert-to-cpp --data-folder=C:/Github/TEAM_Armigoxx/ARMigo/Library/Bee/artifacts/Android/il2cppOutput/data --generatedcppdir=C:/Github/TEAM_Armigoxx/ARMigo/Library/Bee/artifacts/Android/il2cppOutput/cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile=unityaot-linux --profiler-report --profiler-output-file=C:/Github/TEAM_Armigoxx/ARMigo/Library/Bee/artifacts/il2cpp_conv_8f25.traceevents --print-command-line
Error: IL2CPP error (no further information about what managed code was being converted is available)
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Unity.IL2CPP.DataModel.BuildLogic.DataModelBuilder.Initialize(UnderConstruction`2& systemAssembly)
   at Unity.IL2CPP.DataModel.BuildLogic.DataModelBuilder.Build()
   at Unity.IL2CPP.AssemblyConversion.Phases.InitializePhase.Run(AssemblyConversionContext context)
   at Unity.IL2CPP.AssemblyConversion.Classic.ClassicConverter.Run(AssemblyConversionContext context)
   at Unity.IL2CPP.AssemblyConversion.AssemblyConverter.ConvertAssemblies(AssemblyConversionInputData data, AssemblyConversionParameters parameters, AssemblyConversionInputDataForTopLevelAccess dataForTopLevel)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

```

**Comment by livmeraki** [comment]
시은 빌드 문제

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':launcher'.
> Could not resolve all artifacts for configuration ':launcher:classpath'.
   > Could not find com.android.tools.build:gradle:6.1.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/6.1.1/gradle-6.1.1.pom
       - https://jcenter.bintray.com/com/android/tools/build/gradle/6.1.1/gradle-6.1.1.pom
     Required by:
         project :launcher

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

**Comment by Jeremy-0204** [comment]
포톤 아직 적용 안한 Google 로그인 빌드는 잘 됨
Android Force Resolve 할 때 뜨는 창:

```
Running Gradle...

C:\Github\TEAM_Armigoxx\ARMigo\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "C:\Github\TEAM_Armigoxx\ARMigo\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=C:\Program Files\Unity\Hub\Editor\2021.3.6f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK" "-PTARGET_DIR=C:\Github\TEAM_Armigoxx\ARMigo\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///C:/Github/TEAM_Armigoxx/ARMigo/Assets/Firebase/m2repository" "-PPACKAGES_TO_COPY=com.google.firebase:firebase-common:20.1.1;com.google.firebase:firebase-analytics:21.1.0;com.google.android.gms:play-services-base:18.1.0;com.google.firebase:firebase-app-unity:9.3.0;com.google.firebase:firebase-auth:21.0.6;com.google.firebase:firebase-auth-unity:9.3.0;com.google.firebase:firebase-database:20.0.5;com.google.firebase:firebase-database-unity:9.3.0" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=4.0.1"
Executing command: C:\Github\TEAM_Armigoxx\ARMigo\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "C:\Github\TEAM_Armigoxx\ARMigo\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=C:\Program Files\Unity\Hub\Editor\2021.3.6f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK" "-PTARGET_DIR=C:\Github\TEAM_Armigoxx\ARMigo\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///C:/Github/TEAM_Armigoxx/ARMigo/Assets/Firebase/m2repository" "-PPACKAGES_TO_COPY=com.google.firebase:firebase-common:20.1.1;com.google.firebase:firebase-analytics:21.1.0;com.google.android.gms:play-services-base:18.1.0;com.google.firebase:firebase-app-unity:9.3.0;com.google.firebase:firebase-auth:21.0.6;com.google.firebase:firebase-auth-unity:9.3.0;com.google.firebase:firebase-database:20.0.5;com.google.firebase:firebase-database-unity:9.3.0" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=4.0.1"
```

baseProjectTemplate.gradle 파일내용
```
allprojects {
    buildscript {
        repositories {**ARTIFACTORYREPOSITORY**
            google()
            jcenter()
        }

        dependencies {
            // If you are changing the Android Gradle Plugin version, make sure it is compatible with the Gradle version preinstalled with Unity
            // See which Gradle version is preinstalled with Unity here https://docs.unity3d.com/Manual/android-gradle-overview.html
            // See official Gradle and Android Gradle Plugin compatibility table here https://developer.android.com/studio/releases/gradle-plugin#updating-gradle
            // To specify a custom Gradle version in Unity, go do "Preferences > External Tools", uncheck "Gradle Installed with Unity (recommended)" and specify a path to a custom Gradle version
            classpath 'com.android.tools.build:gradle:3.4.3'
            **BUILD_SCRIPT_DEPS**
        }
    }

    repositories {**ARTIFACTORYREPOSITORY**
        google()
        jcenter()
        flatDir {
            dirs "${project(':unityLibrary').projectDir}/libs"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by LeeMineo** [comment]
파이어베이스 겹치는 버전을 지우고 
<img width="335" alt="스크린샷 2022-08-16 오후 3 38 01" src="https://user-images.githubusercontent.com/103713510/184813809-7d2d4f8c-101a-45a1-b3a3-b1a17acdd178.png">
이거버전을 맞추어 주면 해결!
